[package]
name = "cfg-exif"
description = "Conditional compilation in expressions"
version = "0.5.0"
edition = "2021"
license-file = "./UNLICENSE"
repository = "https://github.com/raviqqe/cfg-exif"

[features]
foo = []
bar = []
baz = []

[workspace.lints.rust]
missing_docs = "deny"
warnings = "deny"
